version: "2.4"

services:
  redis:
    image: redis:7-alpine
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
    logging:
      options:
        max-size: "10m"
        max-file: "3"

  postgres:
    image: postgres:15-alpine
    restart: always
    volumes:
      - ./db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: "ytdlbot"
      POSTGRES_USER: "ytdlbot"
      POSTGRES_PASSWORD: "ytdlbot"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ytdlbot -d ytdlbot"]
      interval: 10s
      timeout: 5s
      retries: 3
    logging:
      options:
        max-size: "10m"
        max-file: "3"

  ytdl:
    image: bennythink/ytdlbot
    env_file:
      - .env
    restart: always
    volumes:
      - ./youtube-cookies.txt:/app/youtube-cookies.txt
    depends_on:
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy
